### ISSUE TITLE
:robot: Make 161 URLs point to new website 

### ISSUE THREAD

**Issue by jameshughes89** [jameshughes89/cs101#27]
### Related Issues or PRs
Related-ish #26 

### What 
Currently the csci161.com & csci161.ca urls point to the old website. Also, update old website to just be a link to the new one. 

New website modsurski.com/csci161/

### Why
It's better this way. 

### Where
domains site and old server

**Comment by twentylemon** [comment]
> ### Additional Notes
> If applicable, replace this text with additional notes.

**Comment by jameshughes89** [comment]
Ended up just doing this now.
