### ISSUE TITLE
:new: Turn off Generative AI on Colab

### ISSUE THREAD

**Issue by jameshughes89** [jameshughes89/cs101#630]
### What

Warn students to turn off the generative AI in colab

### Why

1. It's doing too much work for them that it can take away their opportunity to learn things
2. It can be wrong, which will throw them off (e.g. it was wrong at calculating the subtended area)

### Where

In an early topic and a lab. 

### How

Settings -> AI Assistance
![image](https://github.com/user-attachments/assets/c6a73c32-5db0-4621-9e7c-bcd47c947bf6)

### Additional Notes

If applicable, replace this text with additional notes.

**Comment by twentylemon** [comment]
Alternatives should also be investigated. The fact it's there will guarantee its getting used by students.
