### ISSUE TITLE
:bug: Assignment3 Reference did not work; fix reference 

### ISSUE THREAD

**Issue by jameshughes89** [jameshughes89/cs101#86]
### Related Issues or PRs
Got broken in #77 

### What 
Looks like the reference did not work for aliasing. It's gotta' get fixed. 

### Why
Because it's broken

### Where
In the warning at the top of Assignment3 

### How
I'll have to look into how to do it _correctly_.

**Comment by twentylemon** [comment]
Looking at the pr, seems you need to remove the underscore from the reference locations. Docs have a note:

> Reference labels must start with an underscore. When referencing a label, the underscore must be omitted (see examples above).

**Comment by jameshughes89** [comment]
> Looking at the pr, seems you need to remove the underscore from the reference locations. Docs have a note:
> 
> > Reference labels must start with an underscore. When referencing a label, the underscore must be omitted (see examples above).

My man
